const packages = [
  {name:"Essential",price:"5,000",label:"For photographers ready to look established online.",features:["Distinct 1–3 page website","Curated portfolio gallery","Packages and pricing section","WhatsApp enquiry journey","Mobile-first experience","Hosting and technical care","1 content update each month"]},
  {name:"Signature",price:"8,500",label:"For growing brands with more stories and services.",featured:true,features:["Custom website up to 5 pages","Multiple portfolio galleries","Detailed service and package pages","Testimonials and social links","WhatsApp enquiry journey","Hosting and technical care","2 content updates each month","Foundational search setup"]},
  {name:"Studio",price:"12,500",label:"For studios with larger portfolios and regular changes.",features:["Expanded custom website","Advanced gallery collections","Multiple service categories","Priority support","WhatsApp conversion setup","Hosting and technical care","Up to 4 updates each month","Performance and search setup"]}
];
const faqs = [
  ["Why is this a monthly service?","Your monthly payment covers the website design, hosting, maintenance, technical care and ongoing content updates. You avoid a large development payment and never need to manage the website yourself."],
  ["Is there an upfront website development fee?","No large development fee. Your first monthly payment starts the project. Your domain registration or renewal is charged separately."],
  ["Is there a minimum commitment?","Yes. The service has a six-month minimum term. This gives us enough time to build, launch and properly support your website while keeping the upfront cost low."],
  ["Will my website look like every other photographer’s website?","No. We reuse a reliable technical system, but your typography, colours, page composition and gallery treatment are designed around your own photography and brand."],
  ["How do I send new portfolio images?","Simply send the selected images and instructions through WhatsApp. We optimise them for fast loading and add them to the correct gallery."],
  ["Can I change my photography packages and prices?","Yes. Text, price, package and portfolio changes are included within the monthly update allowance of your selected plan."],
  ["What counts as one monthly update?","One update can include a small group of related changes, such as replacing up to 15 gallery images, updating one package, or changing existing text and contact details."],
  ["What happens if I need more updates?","We will confirm the additional cost before starting. You can also move to a higher plan if you regularly need more changes."],
  ["Who owns the domain and photographs?","You own your domain, photographs, logo and written content. Kalana Square retains ownership of its reusable website framework and development system."],
  ["Can customers book directly through the website?","The standard journey sends potential clients to your WhatsApp with a clear enquiry prompt. A full booking or payment system can be added as a separately priced upgrade."],
  ["How quickly can my website be launched?","Most Essential websites can be prepared within 7–10 working days after all photographs, packages, branding and contact details are received."],
  ["What happens if I cancel?","After the six-month minimum term, you can cancel with 30 days’ notice. Your domain remains yours, while the managed website stays active only while the subscription is maintained."]
];
export default function Home(){return <main>
  <header className="siteHeader shell"><a className="wordmark" href="#top"><strong>KALANA SQUARE</strong><span>PHOTOGRAPHY WEBSITES</span></a><nav><a href="#why">Why it works</a><a href="#process">Process</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><a className="miniCta" href="#pricing">Explore plans ↗</a></header>
  <section className="hero shell" id="top"><div className="heroTop"><p className="kicker">MANAGED WEBSITES FOR SRI LANKAN PHOTOGRAPHERS</p><h1>Let your work make the <em>first impression.</em></h1><div className="heroIntro"><p>A considered, modern website that shows your portfolio, explains your packages and moves the right clients into WhatsApp.</p><a className="pill dark" href="#pricing">View monthly plans</a></div></div><div className="heroImage"><img src="https://images.unsplash.com/photo-1611093793031-46db535bde90?fm=jpg&fit=crop&w=1800&q=86" alt="Professional photographer preparing a camera in a bright studio"/><div className="imageNote"><span>01</span><p>Portfolio.<br/>Packages.<br/>Enquiries.</p></div></div><div className="heroFoot"><p>No large development fee</p><p>Designed around your brand</p><p>Updated for you</p></div></section>
  <section className="manifesto" id="why"><div className="shell"><p className="kicker light">MORE THAN A LINK</p><h2>People judge the quality of your photography before they ever message you.</h2><div className="manifestoText"><p>A PDF explains your prices. A well-designed website builds desire, presents your value and gives potential clients the confidence to enquire.</p><p>Your website becomes the professional home for every Facebook post, Instagram bio, referral and WhatsApp conversation.</p></div></div></section>
  <section className="value shell"><div className="sectionTitle"><p className="kicker">WHY LKR 5,000 MAKES SENSE</p><h2>A small monthly investment in how your business is perceived.</h2></div><div className="valueLead"><div className="daily"><strong>≈ LKR 167</strong><span>per day</span></div><p>For less than the cost of many daily business expenses, your photography brand has a professionally designed and continuously managed online presence.</p></div><div className="valueGrid"><article><span>01</span><h3>Look established</h3><p>Give potential clients one polished place to understand your style, experience and packages.</p></article><article><span>02</span><h3>Save your time</h3><p>No page builders, image compression, hosting issues or price-list edits for you to manage.</p></article><article><span>03</span><h3>Support every enquiry</h3><p>Send one professional link instead of repeatedly explaining your work through messages and PDFs.</p></article><article><span>04</span><h3>Keep it current</h3><p>Your best work and latest packages can change as your photography business grows.</p></article></div><div className="roi"><p>One good booking could cover the website for months.</p><span>The website does not replace your marketing. It helps the attention you already earn convert into confidence and enquiries.</span></div></section>
  <section className="process" id="process"><div className="shell"><div className="sectionTitle split"><div><p className="kicker light">A SIMPLE, MANAGED PROCESS</p><h2>You photograph.<br/><em>We handle the website.</em></h2></div><p>Everything is organised through a straightforward WhatsApp workflow. You remain in control without becoming the website manager.</p></div><div className="processRows"><article><span>01</span><h3>Choose</h3><p>Select the plan that matches your portfolio and update needs.</p></article><article><span>02</span><h3>Share</h3><p>Send your logo, photographs, packages and business information.</p></article><article><span>03</span><h3>Review</h3><p>We create a branded website and send it to you for approval.</p></article><article><span>04</span><h3>Stay current</h3><p>Message us whenever approved content needs to be updated.</p></article></div></div></section>
  <section className="pricing" id="pricing"><div className="shell"><div className="pricingHead"><p className="kicker">CLEAR MONTHLY PLANS</p><h2>Choose the level of support your photography business needs.</h2><p>Every plan includes design, hosting, maintenance and a direct line for content updates.</p></div><div className="plans">{packages.map(p=><article className={"plan "+(p.featured?"featured":"")} key={p.name}>{p.featured&&<span className="popular">MOST CHOSEN</span>}<p className="planName">{p.name}</p><div className="price"><small>LKR</small><strong>{p.price}</strong><span>/ month</span></div><p className="planLabel">{p.label}</p><a className={"pill "+(p.featured?"cream":"dark")} href="#contact">Choose {p.name}</a><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul></article>)}</div><p className="planFine">Six-month minimum term. Domain registration or renewal is billed separately. Additional or major development is quoted before work begins.</p></div></section>
  <section className="futurePortfolio shell"><div><p className="kicker">SELECTED PHOTOGRAPHY WEBSITES</p><h2>Proof should be seen, not simply promised.</h2></div><div><p>Our photography website portfolio is being curated with real client work and a new Sri Lankan photography concept project.</p><span>Portfolio collection coming next.</span></div></section>
  <section className="faq" id="faq"><div className="shell faqLayout"><div className="faqIntro"><p className="kicker">BEFORE YOU BEGIN</p><h2>Everything you may want to ask.</h2><p>Clear expectations make a better working relationship. If your question is not here, message us directly.</p></div><div className="faqList">{faqs.map(([q,a],i)=><details key={q}><summary><span>{String(i+1).padStart(2,"0")}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></div></section>
  <section className="contact shell" id="contact"><p className="kicker light">START WITH A CONVERSATION</p><h2>Your photography already has a style.<br/><em>Your website should too.</em></h2><p>Tell us what you photograph and share your current portfolio. We’ll recommend the most suitable plan.</p><a className="pill cream" href="#pricing">Start on WhatsApp ↗</a><small>WhatsApp number will be connected before advertising.</small></section>
  <footer className="shell"><div className="wordmark"><strong>KALANA SQUARE</strong><span>PHOTOGRAPHY WEBSITES</span></div><p>Managed photography websites for Sri Lanka.</p><p>© 2026 Kalana Square</p></footer>
</main>}
