const packages = [
  {name:"Essential",price:"5,000",label:"For photographers ready to look established online.",checkoutUrl:"https://www.kalanasquare.space/checkout/subscribe?cartToken=TyU11oQyRTWg8Yah4fD7LzDNnRwmYhRUxFjT1ueB",features:["Distinct 1–3 page website","Curated portfolio gallery","Packages and pricing section","WhatsApp enquiry journey","Mobile-first experience","Custom domain connection","Hosting and technical care","Image speed optimisation","Basic visitor analytics","3 content updates each month"]},
  {name:"Signature",price:"8,500",label:"For growing brands with more stories and services.",checkoutUrl:"https://www.kalanasquare.space/photography-packages/p/signature-website-care",featured:true,features:["Custom website up to 5 pages","Multiple portfolio galleries","Detailed service and package pages","Testimonials and social links","WhatsApp enquiry journey","Custom domain connection","Hosting and technical care","Image speed optimisation","Basic visitor analytics","Foundational search setup","5 content updates each month","Priority update queue"]},
  {name:"Studio",price:"12,500",label:"For studios with larger portfolios and regular changes.",checkoutUrl:"https://www.kalanasquare.space/photography-packages/p/studio-website-care",features:["Expanded custom website","Advanced gallery collections","Multiple service categories","Team or studio profiles","Campaign landing section","WhatsApp conversion setup","Custom domain connection","Hosting and technical care","Advanced image optimisation","Visitor analytics summary","Performance and search setup","7 content updates each month","Priority support"]}
];
const whatsappUrl="https://wa.me/94714950315?text=Hello%20Kalana%20Square%2C%20I%27m%20interested%20in%20a%20managed%20photography%20website.%20Can%20you%20help%20me%20choose%20the%20right%20package%3F";
const featureInfo:Record<string,string>={
  "Distinct 1–3 page website":"A branded homepage plus the essential pages your photography business needs.",
  "Custom website up to 5 pages":"A larger custom website with space for your story, services, portfolio and contact journey.",
  "Expanded custom website":"A more extensive website structure planned around a studio with several services or audiences.",
  "Curated portfolio gallery":"Your strongest photographs are organised into a polished, easy-to-view gallery.",
  "Multiple portfolio galleries":"Separate galleries for categories such as weddings, portraits, events or commercial work.",
  "Advanced gallery collections":"Larger structured collections with multiple photography categories and visual stories.",
  "Packages and pricing section":"Your services, starting prices and package inclusions are presented clearly.",
  "Detailed service and package pages":"Dedicated space to explain each service, package and ideal client in greater detail.",
  "Multiple service categories":"Separate presentation for each major photography service offered by your studio.",
  "WhatsApp enquiry journey":"Strategic buttons open WhatsApp with a helpful pre-written enquiry message.",
  "WhatsApp conversion setup":"More targeted WhatsApp buttons and messages matched to different services and packages.",
  "Mobile-first experience":"The layout is carefully adapted for people arriving from Facebook and Instagram on phones.",
  "Custom domain connection":"We connect and manage your standard business domain as part of the monthly plan, whether we purchase it for you or you provide access to a domain you already own.",
  "Hosting and technical care":"We keep the website online, maintained and technically healthy while your subscription is active.",
  "Image speed optimisation":"New portfolio images are compressed and prepared to load quickly without unnecessary quality loss.",
  "Advanced image optimisation":"Larger image collections receive structured optimisation and gallery performance care.",
  "Basic visitor analytics":"See basic traffic information such as visits and popular pages when analytics is connected.",
  "Visitor analytics summary":"A simple periodic overview of useful website traffic and visitor behaviour.",
  "Foundational search setup":"Page titles, descriptions and basic structure are prepared for search engines.",
  "Performance and search setup":"Additional performance checks and a broader foundational search setup for larger websites.",
  "Testimonials and social links":"Client feedback and social profiles are integrated to strengthen trust.",
  "Priority update queue":"Your requested updates are placed ahead of Essential-plan update requests.",
  "Priority support":"Your support and update requests receive the fastest available response level.",
  "Team or studio profiles":"Introduce photographers, editors or other studio team members professionally.",
  "Campaign landing section":"A focused section for a seasonal offer, mini-session or photography campaign.",
  "3 content updates each month":"Up to three separate update requests every billing month.",
  "5 content updates each month":"Up to five separate update requests every billing month.",
  "7 content updates each month":"Up to seven separate update requests every billing month."
};
const faqs = [
  ["Why is this a monthly service?","Your monthly payment covers the website design, hosting, maintenance, technical care and ongoing content updates. You avoid a large development payment and never need to manage the website yourself."],
  ["Are there any setup costs or hidden charges?","No. Your selected monthly price covers the website design, standard domain, hosting, maintenance and the included updates. You can start from LKR 5,000 with one clear monthly fee."],
  ["Can I cancel the subscription anytime?","Yes. There is no six-month commitment. You can cancel future renewals at any time. Your website remains active until the end of the period you have already paid for."],
  ["Will my website look like every other photographer’s website?","No. We reuse a reliable technical system, but your typography, colours, page composition and gallery treatment are designed around your own photography and brand."],
  ["How do I send new portfolio images?","Simply send the selected images and instructions through WhatsApp. We optimise them for fast loading and add them to the correct gallery."],
  ["Can I change my photography packages and prices?","Yes. Text, price, package and portfolio changes are included within the monthly update allowance of your selected plan."],
  ["What counts as one monthly update?","One update can include a small group of related changes, such as replacing up to 15 gallery images, updating one package, or changing existing text and contact details."],
  ["What happens if I need more updates?","We will confirm the additional cost before starting. You can also move to a higher plan if you regularly need more changes."],
  ["Will you manage my website for as long as I subscribe?","Yes. While your subscription remains active, we guarantee ongoing hosting, technical care and content-update support within your plan. There is no expiry after the first year."],
  ["What happens if a monthly payment fails?","We keep the website active for a 14-day grace period and contact you so the payment can be corrected. If payment is still outstanding after 14 days, the website may be temporarily paused. It can be restored after the account is brought up to date."],
  ["How will the domain be purchased and managed?","You can choose either option. We can purchase and manage the standard domain for you, or you can purchase it yourself and give us the required access. Your monthly website price remains exactly the same with either option."],
  ["Will this be my own newly designed website?","Yes. You receive a new website designed around your photography, services, colours and brand. Your photographs, logo and written business content remain yours."],
  ["Can customers book directly through the website?","The standard journey sends potential clients to your WhatsApp with a clear enquiry prompt. A full booking or payment system can be added as a separately priced upgrade."],
  ["How quickly can my website be launched?","Most websites can be launched within 5–7 working days after all required photographs, packages, branding and contact details are received."],
  ["What happens after I cancel?","Future monthly renewals stop. The managed website remains active until the end of the period already paid for, and your original photographs and business content remain yours."]
];
export default function Home(){return <main>
  <header className="siteHeader shell"><a className="wordmark" href="#top"><strong>KALANA SQUARE</strong><span>PHOTOGRAPHY WEBSITES</span></a><nav><a href="#why">Why it works</a><a href="#process">Process</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><a className="miniCta" href="#pricing">Explore plans ↗</a></header>
  <section className="hero shell" id="top"><div className="heroTop"><p className="kicker">MANAGED WEBSITES FOR SRI LANKAN PHOTOGRAPHERS</p><h1>Let your work make the <em>first impression.</em></h1><div className="heroIntro"><p>A considered, modern website that shows your portfolio, explains your packages and moves the right clients into WhatsApp.</p><a className="pill dark" href="#pricing">View monthly plans</a></div></div><div className="heroImage"><img src="https://images.unsplash.com/photo-1611093793031-46db535bde90?fm=jpg&fit=crop&w=1800&q=86" alt="Professional photographer preparing a camera in a bright studio"/><div className="imageNote"><span>01</span><p>Portfolio.<br/>Packages.<br/>Enquiries.</p></div></div><div className="heroFoot"><p>No large development fee</p><p>Designed around your brand</p><p>Updated for you</p></div></section>
  <section className="manifesto" id="why"><div className="shell"><p className="kicker light">MORE THAN A LINK</p><h2>People judge the quality of your photography before they ever message you.</h2><div className="manifestoText"><p>Sending a PDF or Google Drive link feels old and transactional. A professionally designed website builds trust, presents your value and gives clients confidence to enquire.</p><p>Your website becomes the credible home for every Facebook post, Instagram bio, referral and WhatsApp conversation.</p></div></div></section>
  <section className="pdfProblem shell"><div className="pdfHeading"><p className="kicker">WHY A PDF IS HOLDING YOU BACK</p><h2>A PDF or Drive link feels like a file.<br/><em>Your photography deserves a professional experience.</em></h2></div><div className="comparison"><div className="comparisonHead"><span>PDF or Google Drive link</span><span>Your professional website</span></div><div><p>Clients must download a file or open another app</p><p>One tap opens instantly in their browser</p></div><div><p>Drive links can create access and permission problems</p><p>A public website works without requesting access</p></div><div><p>Large files can fail or load slowly on mobile</p><p>Optimised pages and images are mobile-friendly</p></div><div><p>Old PDF copies continue circulating after prices change</p><p>Everyone always sees your latest packages</p></div><div><p>Feels outdated and less professional to new clients</p><p>A branded website builds credibility and trust</p></div><div><p>Limited space to communicate your brand and story</p><p>Portfolio, testimonials, packages and brand work together</p></div><div><p>No clear way to guide the next action</p><p>Visitors move directly into a WhatsApp enquiry</p></div></div></section>
  <section className="value shell"><div className="sectionTitle"><p className="kicker">WHY LKR 5,000 MAKES SENSE</p><h2>A small monthly investment in how your business is perceived.</h2></div><div className="valueLead"><div className="daily"><strong>≈ LKR 167</strong><span>per day</span></div><p>For less than the cost of many daily business expenses, your photography brand has a professionally designed and continuously managed online presence.</p></div><div className="valueGrid"><article><span>01</span><h3>Look established</h3><p>Give potential clients one polished place to understand your style, experience and packages.</p></article><article><span>02</span><h3>Save your time</h3><p>No page builders, image compression, hosting issues or price-list edits for you to manage.</p></article><article><span>03</span><h3>Support every enquiry</h3><p>Send one professional link instead of repeatedly explaining your work through messages and PDFs.</p></article><article><span>04</span><h3>Keep it current</h3><p>Your best work and latest packages can change as your photography business grows.</p></article></div><div className="roi"><p>One good booking could cover the website for months.</p><span>The website does not replace your marketing. It helps the attention you already earn convert into confidence and enquiries.</span></div></section>
  <section className="process" id="process"><div className="shell"><div className="sectionTitle split"><div><p className="kicker light">A SIMPLE, MANAGED PROCESS</p><h2>You photograph.<br/><em>We handle the website.</em></h2></div><p>Everything is organised through a straightforward WhatsApp workflow. You remain in control without becoming the website manager.</p></div><div className="processRows"><article><span>01</span><h3>Choose</h3><p>Select the plan that matches your portfolio and update needs.</p></article><article><span>02</span><h3>Share</h3><p>Send your logo, photographs, packages and business information.</p></article><article><span>03</span><h3>Review</h3><p>We create a branded website and send it to you for approval.</p></article><article><span>04</span><h3>Stay current</h3><p>Message us whenever approved content needs to be updated.</p></article></div></div></section>
  <section className="servicePromise shell"><div><p className="kicker">OUR ONGOING PROMISE</p><h2>As long as you subscribe,<br/><em>we keep managing your website.</em></h2></div><div className="promisePoints"><p><span>01</span>Your website remains hosted, monitored and maintained.</p><p><span>02</span>Your included updates renew every billing month.</p><p><span>03</span>A failed payment receives a fair 14-day grace period.</p><p><span>04</span>Your domain and original business content remain yours.</p></div></section>
  <section className="pricing" id="pricing"><div className="shell"><div className="pricingHead"><p className="kicker">CLEAR MONTHLY PLANS</p><h2>Choose the level of support your photography business needs.</h2><p>Every plan includes the website design, standard domain, hosting, maintenance and content updates. No additional or hidden fees.</p></div><div className="plans">{packages.map(p=><article className={"plan "+(p.featured?"featured":"")} key={p.name}>{p.featured&&<span className="popular">MOST CHOSEN</span>}<p className="planName">{p.name}</p><div className="price"><small>LKR</small><strong>{p.price}</strong><span>/ month</span></div><p className="planLabel">{p.label}</p><ul>{p.features.map(f=><li key={f}><span>{f}</span><button className="featureTip" aria-label={"More information about "+f}>i<span role="tooltip">{featureInfo[f]}</span></button></li>)}</ul><a className={"pill "+(p.featured?"cream":"dark")} href={p.checkoutUrl} target="_blank" rel="noreferrer">Subscribe to {p.name} ↗</a></article>)}</div><p className="planFine">One clear monthly price. No setup cost, no hidden fees and no minimum-term commitment. Cancel future renewals anytime.</p></div></section>
  <section className="futurePortfolio shell"><div><p className="kicker">SELECTED PHOTOGRAPHY WEBSITES</p><h2>Proof should be seen, not simply promised.</h2></div><div><p>Our photography website portfolio is being curated with real client work and a new Sri Lankan photography concept project.</p><span>Portfolio collection coming next.</span></div></section>
  <section className="faq" id="faq"><div className="shell faqLayout"><div className="faqIntro"><p className="kicker">BEFORE YOU BEGIN</p><h2>Everything you may want to ask.</h2><p>Clear expectations make a better working relationship. If your question is not here, contact us directly.</p><a className="pill dark faqContact" href={whatsappUrl} target="_blank" rel="noreferrer">Ask on WhatsApp ↗</a></div><div className="faqList">{faqs.map(([q,a],i)=><details key={q}><summary><span>{String(i+1).padStart(2,"0")}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></div></section>
  <section className="contact shell" id="contact"><p className="kicker light">START WITH A CONVERSATION</p><h2>Your photography already has a style.<br/><em>Your website should too.</em></h2><p>Tell us what you photograph and share your current portfolio. We’ll recommend the most suitable plan.</p><a className="pill cream" href={whatsappUrl} target="_blank" rel="noreferrer">Start on WhatsApp ↗</a><small>WhatsApp: +94 71 495 0315</small></section>
  <footer className="shell"><div className="wordmark"><strong>KALANA SQUARE</strong><span>PHOTOGRAPHY WEBSITES</span></div><p>Managed photography websites for Sri Lanka.</p><p>© 2026 Kalana Square</p></footer>
</main>}
